name: Run CI
on:
  pull_request
      
jobs:
  build:
    name: Build Project
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - name: Set Gems
      run: |
        gem install bundler
        bundle install

    - name: Build
      run: |
        xcodebuild build \
        -scheme iOSGitHubActions \
        -destination 'platform=iOS Simulator,name=iPhone 11 Pro' \
        | xcpretty
